package dev.aether.manager.ads

import android.content.Context
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.os.Build
import android.provider.Settings
import dev.aether.manager.NativeAether

object AdBlockChecker {

    private val dnsKeywords: List<String> by lazy {
        if (NativeAether.tryLoad()) {
            NativeAether.nativeGetAdblockDnsKeywords()
                .toList()
                .filter { kw -> kw !in SAFE_DNS_KEYWORDS }
        } else emptyList()
    }

    private val hostsSignatures: List<String> by lazy {
        if (NativeAether.tryLoad()) {
            NativeAether.nativeGetHostsSignatures()
                .toList()
                .filter { sig -> sig !in GENERIC_HOSTS_SIGNATURES }
        } else emptyList()
    }

    /**
     * DNS yang diketahui aman / bukan adblock.
     * Quad9 = privacy DNS biasa. Mullvad = VPN umum, bukan adblock.
     */
    private val SAFE_DNS_KEYWORDS = setOf("quad9", "mullvad")

    /**
     * Signatures hosts yang terlalu generic atau bukan fingerprint adblock tool —
     * dibuang dari pengecekan agar tidak false-positive.
     *
     * "generated by"       — terlalu generic, bisa dari modifikasi sistem lain.
     * "unityads"           — domain iklan yang di-block, bukan nama adblock tool;
     *                        muncul di hosts file yang di-block oleh AdAway/dll.,
     *                        tapi tidak bisa jadi fingerprint tunggal.
     * "ad.doubleclick.net" — sama, domain iklan bukan nama tool.
     * "admob"              — idem.
     *
     * Yang dipertahankan sebagai fingerprint valid: "adaway", "adblock"
     * (nama tool yang eksplisit dituliskan di header file hosts mereka).
     */
    private val GENERIC_HOSTS_SIGNATURES = setOf(
        "generated by",
        "unityads",
        "ad.doubleclick.net",
        "admob"
    )

    /** true jika terdeteksi Private DNS adblock aktif (DoT hostname-based). */
    fun isDnsAdblockActive(ctx: Context): Boolean {
        // Hanya periksa Private DNS hostname — bukan mode, bukan IP DNS.
        // IP DNS tidak reliable: bisa sama antara adblock dan non-adblock provider.
        val privateDnsHost = Settings.Global.getString(
            ctx.contentResolver,
            "private_dns_specifier"
        )?.lowercase() ?: return false

        // Mode harus "hostname" agar custom DoT aktif
        val privateDnsMode = Settings.Global.getString(
            ctx.contentResolver,
            "private_dns_mode"
        )
        if (privateDnsMode != "hostname") return false

        return dnsKeywords.any { kw -> privateDnsHost.contains(kw) }
    }

    /**
     * true jika /etc/hosts mengandung signature adblock yang spesifik.
     * Domain iklan dan string generic sudah difilter via GENERIC_HOSTS_SIGNATURES.
     */
    fun isHostsModified(): Boolean {
        if (hostsSignatures.isEmpty()) return false
        val hostsContent = readHostsFile() ?: return false
        return hostsSignatures.any { sig -> hostsContent.contains(sig, ignoreCase = true) }
    }

    private fun readHostsFile(): String? {
        try {
            val content = java.io.File("/etc/hosts").readText()
            if (content.isNotBlank()) return content
        } catch (_: Exception) {}

        return try {
            val result = com.topjohnwu.superuser.Shell.cmd("cat /etc/hosts").exec()
            if (result.isSuccess) result.out.joinToString("\n").takeIf { it.isNotBlank() }
            else null
        } catch (_: Exception) {
            null
        }
    }

    /**
     * VPN-based adblock detection — hanya flag jika VPN aktif DAN
     * DNS server-nya mengandung keyword adblock yang dikenal.
     *
     * VPN biasa (work VPN, WireGuard personal, Mullvad tanpa adblock DNS)
     * tidak akan ter-detect sebagai adblock.
     */
    fun isVpnWithAdblockDns(ctx: Context): Boolean {
        return try {
            val cm = ctx.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager

            val vpnActive = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                val activeNetwork = cm.activeNetwork ?: return false
                val caps = cm.getNetworkCapabilities(activeNetwork) ?: return false
                caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN)
            } else {
                @Suppress("DEPRECATION")
                cm.getNetworkInfo(android.net.ConnectivityManager.TYPE_VPN)?.isConnected == true
            }

            if (!vpnActive) return false

            // VPN aktif — cek DNS-nya; hanya flag jika DNS mengandung adblock keyword
            val dnsServers = buildString {
                val lp = cm.getLinkProperties(cm.activeNetwork)
                lp?.dnsServers?.forEach { addr ->
                    append(addr.hostAddress ?: "").append(" ")
                }
            }.lowercase()

            // Adblock VPN biasanya pakai IP DNS yang dikenal: AdGuard, NextDNS, dll
            val vpnAdblockDnsIps = setOf(
                "94.140.14", "94.140.15",   // AdGuard DNS
                "45.90.",                    // NextDNS prefix
                "9.9.9.11", "149.112.112.11" // Quad9 with blocklist
            )
            vpnAdblockDnsIps.any { ip -> dnsServers.contains(ip) } ||
                dnsKeywords.any { kw -> dnsServers.contains(kw) }

        } catch (_: Exception) {
            false
        }
    }

    /**
     * true jika ada adblock aktif.
     * VPN biasa tanpa adblock DNS tidak di-flag.
     */
    fun isAdblockActive(ctx: Context): Boolean =
        isDnsAdblockActive(ctx) || isHostsModified() || isVpnWithAdblockDns(ctx)
}
