package dev.aether.manager.ads

import android.content.Context
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.os.Build
import android.provider.Settings
import dev.aether.manager.NativeAether

//
// The adblock detection relies on native helpers provided by libaether.so.  In some
// configurations the native library may not be loaded when this object is first
// referenced (for example split APK installs can relocate the .so outside of
// the default search path).  To improve resiliency we compute the adblock
// signature lists on demand within the detection functions using the provided
// context.  This allows NativeAether.tryLoad(ctx) to leverage a context-based
// fallback path to locate the library.  If the library still fails to load
// (e.g. missing on the device) the resulting lists will be empty and the
// detection methods will simply return false rather than crashing or showing
// incorrect ads.

private fun getDnsKeywords(ctx: Context): List<String> {
    return if (NativeAether.tryLoad(ctx)) {
        NativeAether.nativeGetAdblockDnsKeywords()
            .toList()
            .filter { kw -> kw !in SAFE_DNS_KEYWORDS }
    } else emptyList()
}

private fun getHostsSignatures(ctx: Context): List<String> {
    return if (NativeAether.tryLoad(ctx)) {
        NativeAether.nativeGetHostsSignatures()
            .toList()
            .filter { sig -> sig !in GENERIC_HOSTS_SIGNATURES }
    } else emptyList()
}

object AdBlockChecker {

    // The keyword and signature lists were previously held as global lazy
    // properties.  However, without a Context the native loader cannot
    // leverage its fallback mechanism and thus may silently fail to load
    // libaether.so.  Instead the lists are computed on demand via
    // getDnsKeywords(ctx) and getHostsSignatures(ctx) so that a Context can
    // be passed into NativeAether.tryLoad().

    /**
     * DNS yang diketahui aman / bukan adblock.
     * Quad9 = privacy DNS biasa. Mullvad = VPN umum, bukan adblock.
     */
    private val SAFE_DNS_KEYWORDS = setOf("quad9", "mullvad")

    /**
     * Signatures hosts yang terlalu generic — bisa muncul dari modifikasi
     * sistem lain yang tidak ada hubungannya dengan adblock.
     */
    private val GENERIC_HOSTS_SIGNATURES = setOf("generated by")

    /** true jika terdeteksi Private DNS adblock aktif (DoT hostname-based). */
    fun isDnsAdblockActive(ctx: Context): Boolean {
        // Hanya periksa Private DNS hostname — bukan mode, bukan IP DNS.
        // IP DNS tidak reliable: bisa sama antara adblock dan non‑adblock provider.
        val privateDnsHost = Settings.Global.getString(
            ctx.contentResolver,
            "private_dns_specifier"
        )?.lowercase() ?: return false

        // Mode harus "hostname" agar custom DoT aktif
        val privateDnsMode = Settings.Global.getString(
            ctx.contentResolver,
            "private_dns_mode"
        )
        if (privateDnsMode != "hostname") return false

        // Compute keywords on demand using the supplied context
        val keywords = getDnsKeywords(ctx)
        return keywords.any { kw -> privateDnsHost.contains(kw) }
    }

    /**
     * true jika /etc/hosts mengandung signature adblock yang spesifik.
     * "generated by" dihapus dari pengecekan — terlalu generic.
     *
     * Passing the context allows the native library loader to fall back to
     * the correct library directory if needed.  If the library fails to
     * load, the signature list will be empty and this returns false.
     */
    fun isHostsModified(ctx: Context): Boolean {
        val signatures = getHostsSignatures(ctx)
        if (signatures.isEmpty()) return false
        val hostsContent = readHostsFile() ?: return false
        return signatures.any { sig -> hostsContent.contains(sig, ignoreCase = true) }
    }

    private fun readHostsFile(): String? {
        try {
            val content = java.io.File("/etc/hosts").readText()
            if (content.isNotBlank()) return content
        } catch (_: Exception) {}

        return try {
            val result = com.topjohnwu.superuser.Shell.cmd("cat /etc/hosts").exec()
            if (result.isSuccess) result.out.joinToString("\n").takeIf { it.isNotBlank() }
            else null
        } catch (_: Exception) {
            null
        }
    }

    /**
     * VPN-based adblock detection — hanya flag jika VPN aktif DAN
     * DNS server-nya mengandung keyword adblock yang dikenal.
     *
     * VPN biasa (work VPN, WireGuard personal, Mullvad tanpa adblock DNS)
     * tidak akan ter-detect sebagai adblock.
     */
    fun isVpnWithAdblockDns(ctx: Context): Boolean {
        return try {
            val cm = ctx.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager

            val vpnActive = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                val activeNetwork = cm.activeNetwork ?: return false
                val caps = cm.getNetworkCapabilities(activeNetwork) ?: return false
                caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN)
            } else {
                @Suppress("DEPRECATION")
                cm.getNetworkInfo(android.net.ConnectivityManager.TYPE_VPN)?.isConnected == true
            }

            if (!vpnActive) return false

            // VPN aktif — cek DNS-nya; hanya flag jika DNS mengandung adblock keyword
            val dnsServers = buildString {
                val lp = cm.getLinkProperties(cm.activeNetwork)
                lp?.dnsServers?.forEach { addr ->
                    append(addr.hostAddress ?: "").append(" ")
                }
            }.lowercase()

            // Adblock VPN biasanya pakai IP DNS yang dikenal: AdGuard, NextDNS, dll
            val vpnAdblockDnsIps = setOf(
                "94.140.14", "94.140.15",   // AdGuard DNS
                "45.90.",                    // NextDNS prefix
                "9.9.9.11", "149.112.112.11" // Quad9 with blocklist
            )
            val keywords = getDnsKeywords(ctx)
            vpnAdblockDnsIps.any { ip -> dnsServers.contains(ip) } ||
                keywords.any { kw -> dnsServers.contains(kw) }

        } catch (_: Exception) {
            false
        }
    }

    /**
     * true jika ada adblock aktif.
     * VPN biasa tanpa adblock DNS tidak di-flag.
     */
    fun isAdblockActive(ctx: Context): Boolean =
        isDnsAdblockActive(ctx) || isHostsModified(ctx) || isVpnWithAdblockDns(ctx)
}