package dev.aether.manager.ads

import android.content.Context
import android.content.pm.PackageManager

//
// AdBlock detection — mendeteksi aplikasi atau tool yang benar-benar memblokir iklan.
//
// Yang TIDAK di-flag:
//   - Private DNS ke provider seperti AdGuard DNS, NextDNS, Cloudflare, dll
//     → Itu hanya DNS privat/enkripsi, bukan pemblokir iklan
//   - VPN biasa (WireGuard, OpenVPN, dsb) tanpa komponen adblock
//
// Yang di-flag:
//   1. Aplikasi adblock terinstall (package name match)
//   2. Modified /etc/hosts dengan signature adblock yang spesifik

// ─── Package name aplikasi adblock yang dikenal ───────────────────────────────
// Hanya aplikasi yang secara eksplisit memblokir iklan di level sistem/app.
// DNS provider (AdGuard DNS, NextDNS, dll) TIDAK termasuk di sini.
private val ADBLOCK_PACKAGES = setOf(
    // AdAway — hosts-based adblock (root)
    "org.adaway",

    // Blokada — system-wide adblock via VPN/root
    "org.blokada.alarm",
    "org.blokada.fem.android",
    "org.blokada.origin.alarm",

    // AdGuard app (bukan AdGuard DNS)
    "com.adguard.android",
    "com.adguard.android.contentblocker",

    // DNS66 — hosts-based adblocker via VPN
    "org.jak_linux.dns66",

    // NetGuard dengan adblock
    "eu.faircode.netguard",

    // Rethink DNS + Firewall (firewall + block, bukan DNS-only)
    "com.celzero.bravedns",

    // personalDNSfilter
    "dnsfilter.android",

    // TrackerControl
    "net.kollnig.missioncontrol.fdroid",
    "net.kollnig.missioncontrol.play",

    // InviZible Pro
    "pan.alexander.tordnscrypt",
    "pan.alexander.tordnscrypt.stable",
    "pan.alexander.tordnscrypt.gp",

    // Hosts file adblock managers
    "com.fusionbit.hosts",
    "com.majeur.hosts"
)

// ─── Signature hosts file adblock ─────────────────────────────────────────────
// Hanya tanda yang benar-benar spesifik untuk hosts-based adblock.
// TIDAK termasuk "generated by" yang terlalu generic.
private val HOSTS_ADBLOCK_SIGNATURES = setOf(
    // AdAway signatures
    "adaway.org",
    "# adaway",
    "# generated by adaway",

    // StevenBlack hosts
    "stevenblack",

    // Common adblock hosts patterns — spesifik ke ad domain blocking
    "0.0.0.0 adservice.google",
    "0.0.0.0 pagead2.googlesyndication.com",
    "0.0.0.0 ads.google.com",
    "127.0.0.1 adservice.google",
    "127.0.0.1 pagead2.googlesyndication.com",
    "0.0.0.0 doubleclick.net",
    "127.0.0.1 doubleclick.net",
    "0.0.0.0 googleadservices.com",
    "0.0.0.0 googlesyndication.com",
    "0.0.0.0 unity3d.com",
    "0.0.0.0 unityads.unity3d.com",
    "0.0.0.0 ads.unity3d.com"
)

object AdBlockChecker {

    /**
     * true jika ada aplikasi adblock terinstall di device.
     * Tidak memerlukan root. Hanya cek package name.
     */
    fun isAdblockAppInstalled(ctx: Context): Boolean {
        val pm = ctx.packageManager
        return ADBLOCK_PACKAGES.any { pkg ->
            try {
                pm.getPackageInfo(pkg, 0)
                true
            } catch (_: PackageManager.NameNotFoundException) {
                false
            }
        }
    }

    /**
     * true jika /etc/hosts dimodifikasi dengan signature adblock yang spesifik.
     * Memerlukan root untuk membaca hosts jika tidak bisa diakses langsung.
     */
    fun isHostsModified(ctx: Context): Boolean {
        val hostsContent = readHostsFile() ?: return false
        val normalized = hostsContent.lowercase()
        return HOSTS_ADBLOCK_SIGNATURES.any { sig -> normalized.contains(sig.lowercase()) }
    }

    private fun readHostsFile(): String? {
        try {
            val content = java.io.File("/etc/hosts").readText()
            if (content.isNotBlank()) return content
        } catch (_: Exception) {}

        return try {
            val result = com.topjohnwu.superuser.Shell.cmd("cat /etc/hosts").exec()
            if (result.isSuccess) result.out.joinToString("\n").takeIf { it.isNotBlank() }
            else null
        } catch (_: Exception) {
            null
        }
    }

    /**
     * true jika adblock aktif — app terinstall ATAU hosts dimodifikasi.
     *
     * NOTE: Private DNS ke AdGuard DNS, NextDNS, Cloudflare, dll TIDAK dianggap adblock.
     * VPN biasa juga TIDAK dianggap adblock.
     */
    fun isAdblockActive(ctx: Context): Boolean =
        isAdblockAppInstalled(ctx) || isHostsModified(ctx)
}
